language: ruby
rvm:
 - 2.5.1

before_install:
  - gem update --system
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"

install:
  - bundle install

 script:
  - bundle exec rake build
